"""Builds jobquest-items.js: the hand-in items for every class and job quest.
Each entry is [quantity, name, hq, key]. key is 1 for a Key Item, which the quest
provides, so the page shows it but leaves it out of the list it exports.

Source is the local wiki dump (E:\\wiki\\ffxiv_wiki.db). Each Quest infobox in the
"Class & Job Quests" journal section carries a `req-items` field such as
"1 HQ Raptorskin Targe, 10 Maple Sap". The game's own Quest sheet names the item
ids but not the quantity or the HQ flag, which is why the wiki is the source.

Run:  python tools/build_jobquest_items.py
Output: jobquest-items.js, keyed by quest title (the key app.js already uses).
"""
import json
import re
import sqlite3
from pathlib import Path

DB = Path(r"E:\wiki\ffxiv_wiki.db")
OUT = Path(__file__).resolve().parent.parent / "jobquest-items.js"

ENTRY = re.compile(r"^(\d+)\s+(HQ\s+)?(.+)$")


def is_key_item(con, name):
    """True when the wiki's item page types the item as a Key Item.

    Key items are given to you by the quest, or made during it, so nobody can
    prepare them. The page needs an exact title match; a name with no item page
    (most equipment) is treated as a normal item.
    """
    row = con.execute(
        "select infobox_json from pages where title = ? and template_name = 'Item infobox'",
        (name,),
    ).fetchone()
    return bool(row) and json.loads(row[0]).get("type", "").strip().lower() == "key item"


def parse(con, req):
    items = []
    for part in req.split(","):
        part = part.strip()
        m = ENTRY.match(part)
        if not m:
            raise ValueError(f"unparsed req-items entry: {part!r}")
        qty, hq, name = int(m.group(1)), bool(m.group(2)), m.group(3).strip()
        key = name.endswith("(Key Item)")
        if key:
            name = name[: -len("(Key Item)")].strip()
        key = key or is_key_item(con, name)
        items.append([qty, name, 1 if hq else 0, 1 if key else 0])
    return items


def main():
    con = sqlite3.connect(DB)
    out = {}
    for title, raw in con.execute(
        "select title, infobox_json from pages where template_name = 'Quest infobox'"
    ):
        try:
            box = json.loads(raw)
        except (TypeError, ValueError):
            continue
        if box.get("journal-section") != "Class & Job Quests":
            continue
        req = (box.get("req-items") or "").strip()
        if not req:
            continue
        items = parse(con, req)
        if items:
            out[title] = items

    body = json.dumps(out, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    OUT.write_text(
        "// Generated by tools/build_jobquest_items.py from the wiki dump. Do not edit.\n"
        "// title -> [[quantity, item name, 1 if HQ is required, 1 if a Key Item], ...]\n"
        f"const JOBQUEST_ITEMS = {body};\n",
        encoding="utf-8",
    )
    print(f"{len(out)} quests -> {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
